// angular/src/app/visualization/points/points.component.ts
import { Component, Input } from '@angular/core';
import { DURATION, MARKER_RADIUS } from '../../../lib/constant';
import { ClusterPoint } from '../cluster-point/cluster-point.component';

@Component({
  selector: '[app-points]',
  templateUrl: './points.component.html'
})
export class PointsComponent {
  @Input() item: ClusterPoint;
  @Input() isClustered: number;
  markerRadius = MARKER_RADIUS;
  protected transition = t => t.duration(DURATION);

  protected trackByPoint(index: number, obj: object): any {
    return obj[2].id;
  }
}

<svg:g [ngClass]="'point-group'">
  <svg:circle [ngClass]="'marker'" *ngFor="let point of item[2]; index as i; trackBy: trackByPoint"
              [attr.cx.px]="point[0]"
              [attr.cy.px]="point[1]"
              [attr.r.px]="markerRadius"
              [appSvgTransition]="transition"
              [d3-attr]="{
              'fill-opacity': (1 - isClustered) * .25,
              cx: isClustered ? item[0] : point[0],
              cy: isClustered ? item[1] : point[1]
              }"
  >
  </svg:circle>
</svg:g>

// react/src/components/App/Visualization/Points/index.js
import React, {useEffect, useRef} from 'react';
import {makeStyles} from '@material-ui/core';
import {select} from "d3-selection";
import 'd3-transition';
import {DURATION} from "../../../../constant";

const useStyles = makeStyles(theme => ({
    marker: {
        stroke: 'none',
        fill: 'steelblue',
        fillOpacity: .25
    }
}));

const Points = ({points, isClustered}) => {
    const classes = useStyles();
    const pointGroupRef = useRef();

    useEffect(() => {
        if (isClustered) {
            select(pointGroupRef.current)
                .selectAll('circle')
                .transition()
                .duration(DURATION)
                .attr('cx', points[0])
                .attr('cy', points[1])
                .style('fill-opacity', 0);
        }
    }, [isClustered, points]);

    return (
        <g className="original-point-group" ref={pointGroupRef}>
            {
                points[2].map(point => {
                    const [x, y, item] = point;
                    return (
                        <circle key={item.id}
                                className={classes.marker}
                                cx={x}
                                cy={y}
                                r={item.r}/>
                    )
                })
            }
        </g>
    )
};
export default Points;
