// react/src/components/App/Visualization/ClusterPoint/index.js
import React, {useEffect, useRef} from 'react';
import {makeStyles} from '@material-ui/core';
import "d3-transition";
import {select} from "d3-selection";
import Points from "../Points";
import {DURATION, MARKER_RADIUS} from "../../../../constant";

const useStyles = makeStyles(theme => ({
    cluster: {
        stroke: 'none',
        fill: 'steelblue',
        fillOpacity: 0
    },
    clusterPointMarker: {
        fillOpacity: 0
    },
    label: {
        textAnchor: 'middle'
    }
}));

const ClusterPoint = ({clusterPoint, isClustered}) => {
    const classes = useStyles();
    const clusterPointRef = useRef();

    // Retrieve the radius of the point by getting the first point
    const [x, y, pointArray] = clusterPoint;
    const r = MARKER_RADIUS;

    useEffect(() => {
        if (isClustered) {
            select(clusterPointRef.current)
                .select('circle')
                .transition()
                .duration(DURATION)
                .style('fill-opacity', .5);

            select(clusterPointRef.current)
                .select('text')
                .transition()
                .duration(DURATION)
                .style('fill-opacity', 1)
        }

    }, [isClustered]);

    return <g className='group-of-clusters-and-points'>
        <g className={classes.clusterPointMarker}
           ref={clusterPointRef}
           transform={`translate(${x},${y})`}>
            <circle className={classes.cluster}
                    r={r}/>
            {
                pointArray.length > 1 &&
                <text className={classes.label} dy={r / 2}>
                    {pointArray.length}
                </text>
            }
        </g>
        <Points points={clusterPoint} isClustered={isClustered}/>
    </g>
};
export default ClusterPoint;

// angular/src/app/visualization/cluster-point/cluster-point.component.ts
import { Component, Input } from '@angular/core';
import { DURATION, MARKER_RADIUS } from '../../../lib/constant';

export interface ClusterPoint {
  item: [number, number, any[]]
}

@Component({
  selector: '[app-cluster-point]',
  templateUrl: './cluster-point.component.html'
})
export class ClusterPointComponent {
  @Input() item: ClusterPoint;
  @Input() isClustered: number;
  markerRadius = MARKER_RADIUS;
  protected transition = t => t.duration(DURATION);

  get gTransform(): string {
    return `translate(${this.item[0]},${this.item[1]})`;
  }
}

<svg:g [ngClass]="'group-of-clusters-and-points'">
  <svg:g [ngClass]="'cluster-point'" [attr.transform]="gTransform">
    <svg:circle [ngClass]="'cluster'"
                [attr.r.px]="markerRadius"
                [appSvgTransition]="transition"
                [d3-attr]="{'fill-opacity': isClustered * .5}"
    >
    </svg:circle>
    <svg:text *ngIf="item[2].length"
              [ngClass]="'label'"
              [attr.dy]="markerRadius / 2"
              [appSvgTransition]="transition"
              [d3-attr]="{'fill-opacity': isClustered}"
    >
      {{item[2].length}}
    </svg:text>
  </svg:g>
</svg:g>
